server:
  port: 8080

spring:
  application:
    name: shorten
  jpa:
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mariadb://35.238.51.127/URL_SHORTEN?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: cloud1234
